name: CI Healthcheck
on:
  workflow_dispatch:
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Print context
        run: |
          echo "Repo: $GITHUB_REPOSITORY"
          echo "Ref:  $GITHUB_REF_NAME"
      - name: Success
        run: echo "✅ Runner, permissions and YAML are good."
